In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("games.csv", index_col=0)

In [11]:
df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City

In [5]:
df.describe()

,gf,ga,xg,xga,poss,attendance,notes,sh,sot,dist,fk,pk,pkatt,season
count,1605.000000,1605.000000,1605.000000,1605.000000,1605.00000,909.000000,0.0,1605.000000,1605.000000,1604.000000,1605.000000,1605.000000,1605.000000,1605.000000
mean,1.409346,1.368224,1.401931,1.379688,50.23053,37681.237624,NaN,12.416199,4.168847,17.647631,0.456698,0.123988,0.151402,2021.526480
std,1.306052,1.289556,0.817142,0.817086,12.54152,17585.302388,NaN,5.424957,2.435866,3.032722,0.658836,0.355160,0.390193,0.499454
min,0.000000,0.000000,0.000000,0.000000,18.00000,2000.000000,NaN,0.000000,0.000000,5.300000,0.000000,0.000000,0.000000,2021.000000
25%,0.000000,0.000000,0.800000,0.800000,40.00000,25357.000000,NaN,8.000000,2.000000,15.700000,0.000000,0.000000,0.000000,2021.000000
50%,1.000000,1.000000,1.300000,1.300000,50.00000,36166.000000,NaN,12.000000,4.000000,17.600000,0.000000,0.000000,0.000000,2022.000000
75%,2.000000,2.000000,1.900000,1.800000,60.00000,52824.000000,NaN,16.000000,6.000000,19.400000,1.000000,0.000000,0.000000,2022.000000
max,9.000000,9.000000,5.400000,5.400000,82.00000,74147.000000,NaN,31.000000,15.000000,35.000000,4.000000,3.000000,3.000000,2022.000000

In [7]:
df.shape

(1605, 27)

In [15]:
df.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [16]:
df["date"] = pd.to_datetime(df['date'])
df.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [19]:
#covert home/ away to cat 
df['venue_code'] = df['venue'].astype('category').cat.codes #convert string to category then category into numbers
df['opponent_code'] = df['opponent'].astype('category').cat.codes #convert string to category then category into numbers

df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,venue_code,opponent_code
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City,0,23
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City,1,2
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City,0,15
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City,1,7
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City,1,17

In [20]:
df['hour'] = df['time'].str.replace(':.+', "", regex=True).astype('int')

In [21]:
df['day_code'] = df['date'].dt.day_of_week

In [23]:
#convert the target to a boolean 
df['target']= (df['result'] =='W').astype('int')
df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opponent_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,1.0,1.0,2022,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,20,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,7,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,8,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,15,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,5,16,6,1

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [27]:
train = df[df['date'] < '2022-01-01']
test = df[df['date'] > '2022-01-01']

In [30]:
predictors = ['venue_code', 'opponent_code', 'hour', 'day_code']

In [31]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [34]:
preds = rf.predict(test[predictors])

In [36]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(test['target'], preds)
acc

0.5983086680761099

In [37]:
combined = pd.DataFrame(dict(actual = test['target'], predictions = preds))

In [39]:
pd.crosstab(index=combined['actual'], columns=combined['predictions'])

predictions    0   1
actual
0            216  53
1            137  67

In [40]:
from sklearn.metrics import precision_score
precision_score(test['target'], preds)

0.5583333333333333